# Configuracion de conexion al servidor de inventario.
# Cada empleado debe ajustar "host" con la IP del servidor dentro de la VPN.
host=10.8.0.1
puerto=9090
truststore=cliente_truststore.p12
clave_truststore=claveClienteSegura123
